/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicQaRouteImport } from './routes/_public/qa'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicFeedbackRouteImport } from './routes/_public/feedback'
import { Route as PublicDocumentsRouteImport } from './routes/_public/documents'
import { Route as PublicCoursesRouteImport } from './routes/_public/courses'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicBlogRouteImport } from './routes/_public/blog'
import { Route as PublicAchievementsRouteImport } from './routes/_public/achievements'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppStudentDashboardRouteImport } from './routes/_app/student/dashboard'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQaRoute = PublicQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeedbackRoute = PublicFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocumentsRoute = PublicDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAchievementsRoute = PublicAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppStudentDashboardRoute = AppStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/achievements': typeof PublicAchievementsRoute
  '/blog': typeof PublicBlogRoute
  '/contact': typeof PublicContactRoute
  '/courses': typeof PublicCoursesRoute
  '/documents': typeof PublicDocumentsRoute
  '/feedback': typeof PublicFeedbackRoute
  '/login': typeof PublicLoginRoute
  '/qa': typeof PublicQaRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/achievements': typeof PublicAchievementsRoute
  '/blog': typeof PublicBlogRoute
  '/contact': typeof PublicContactRoute
  '/courses': typeof PublicCoursesRoute
  '/documents': typeof PublicDocumentsRoute
  '/feedback': typeof PublicFeedbackRoute
  '/login': typeof PublicLoginRoute
  '/qa': typeof PublicQaRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/achievements': typeof PublicAchievementsRoute
  '/_public/blog': typeof PublicBlogRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/courses': typeof PublicCoursesRoute
  '/_public/documents': typeof PublicDocumentsRoute
  '/_public/feedback': typeof PublicFeedbackRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/qa': typeof PublicQaRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/student/dashboard': typeof AppStudentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/documents'
    | '/feedback'
    | '/login'
    | '/qa'
    | '/student/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/documents'
    | '/feedback'
    | '/login'
    | '/qa'
    | '/student/dashboard'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_public/about'
    | '/_public/achievements'
    | '/_public/blog'
    | '/_public/contact'
    | '/_public/courses'
    | '/_public/documents'
    | '/_public/feedback'
    | '/_public/login'
    | '/_public/qa'
    | '/_public/'
    | '/_app/student/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/qa': {
      id: '/_public/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof PublicQaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/feedback': {
      id: '/_public/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof PublicFeedbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/documents': {
      id: '/_public/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PublicDocumentsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses': {
      id: '/_public/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/achievements': {
      id: '/_public/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof PublicAchievementsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/student/dashboard': {
      id: '/_app/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AppStudentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppStudentDashboardRoute: typeof AppStudentDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudentDashboardRoute: AppStudentDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAchievementsRoute: typeof PublicAchievementsRoute
  PublicBlogRoute: typeof PublicBlogRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicCoursesRoute: typeof PublicCoursesRoute
  PublicDocumentsRoute: typeof PublicDocumentsRoute
  PublicFeedbackRoute: typeof PublicFeedbackRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicQaRoute: typeof PublicQaRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAchievementsRoute: PublicAchievementsRoute,
  PublicBlogRoute: PublicBlogRoute,
  PublicContactRoute: PublicContactRoute,
  PublicCoursesRoute: PublicCoursesRoute,
  PublicDocumentsRoute: PublicDocumentsRoute,
  PublicFeedbackRoute: PublicFeedbackRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicQaRoute: PublicQaRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
