/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const QaLazyRouteImport = createFileRoute('/qa')()
const LoginLazyRouteImport = createFileRoute('/login')()
const FeedbackLazyRouteImport = createFileRoute('/feedback')()
const DocumentsLazyRouteImport = createFileRoute('/documents')()
const CoursesLazyRouteImport = createFileRoute('/courses')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const BlogLazyRouteImport = createFileRoute('/blog')()
const AchievementsLazyRouteImport = createFileRoute('/achievements')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const StudentDashboardLazyRouteImport = createFileRoute('/student/dashboard')()

const QaLazyRoute = QaLazyRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/qa.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const FeedbackLazyRoute = FeedbackLazyRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/feedback.lazy').then((d) => d.Route))
const DocumentsLazyRoute = DocumentsLazyRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/documents.lazy').then((d) => d.Route))
const CoursesLazyRoute = CoursesLazyRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/courses.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const BlogLazyRoute = BlogLazyRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))
const AchievementsLazyRoute = AchievementsLazyRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/achievements.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const StudentDashboardLazyRoute = StudentDashboardLazyRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/student/dashboard.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/achievements': typeof AchievementsLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/feedback': typeof FeedbackLazyRoute
  '/login': typeof LoginLazyRoute
  '/qa': typeof QaLazyRoute
  '/student/dashboard': typeof StudentDashboardLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/achievements': typeof AchievementsLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/feedback': typeof FeedbackLazyRoute
  '/login': typeof LoginLazyRoute
  '/qa': typeof QaLazyRoute
  '/student/dashboard': typeof StudentDashboardLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/achievements': typeof AchievementsLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/courses': typeof CoursesLazyRoute
  '/documents': typeof DocumentsLazyRoute
  '/feedback': typeof FeedbackLazyRoute
  '/login': typeof LoginLazyRoute
  '/qa': typeof QaLazyRoute
  '/student/dashboard': typeof StudentDashboardLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/documents'
    | '/feedback'
    | '/login'
    | '/qa'
    | '/student/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/documents'
    | '/feedback'
    | '/login'
    | '/qa'
    | '/student/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/documents'
    | '/feedback'
    | '/login'
    | '/qa'
    | '/student/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AchievementsLazyRoute: typeof AchievementsLazyRoute
  BlogLazyRoute: typeof BlogLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  CoursesLazyRoute: typeof CoursesLazyRoute
  DocumentsLazyRoute: typeof DocumentsLazyRoute
  FeedbackLazyRoute: typeof FeedbackLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  QaLazyRoute: typeof QaLazyRoute
  StudentDashboardLazyRoute: typeof StudentDashboardLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AchievementsLazyRoute: AchievementsLazyRoute,
  BlogLazyRoute: BlogLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  CoursesLazyRoute: CoursesLazyRoute,
  DocumentsLazyRoute: DocumentsLazyRoute,
  FeedbackLazyRoute: FeedbackLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  QaLazyRoute: QaLazyRoute,
  StudentDashboardLazyRoute: StudentDashboardLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
